version: "2"

 

services:
  precifiquefront:
    image: precifique
    ports:
      - "8090:80"
    restart: always
    networks:
      docker-elk_elk:
networks:
  docker-elk_elk:
    external: true
